steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/civic-gate-353504/bima-image', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/civic-gate-353504/bima-image']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'test-bima', '--image', 'gcr.io/civic-gate-353504/bima-image', '--region', 'asia-southeast2']
images:
- gcr.io/civic-gate-353504/bima-image
